version: '3.8'

services:
  romm:
    image: rommapp/romm
    container_name: romm
    restart: unless-stopped
    environment:
      DB_NAME: 'user'        # 确保与 MariaDB 中的数据库名一致
      DB_USER: 'user'        # 数据库用户名
      DB_PASSWD: 'password'  # 数据库密码
      DB_HOST: '172.17.0.1'       # 使用宿主机 Docker 网关 IP（或实际 MariaDB IP）
      DB_PORT: '3306'             # 显式指定端口（若 MariaDB 使用非默认端口）
      ROMM_AUTH_SECRET_KEY: 'ed26c6055496sccfe34ffff695531b5b0ae62365244797ffb7a2591278593f49' # 通过 openssl rand -hex 32 生成
#      IGDB_CLIENT_ID:   ''          # 在 IGDB 注册应用以获取 ID 和 SECRET
#      IGDB_CLIENT_SECRET:  ''       # https://api-docs.igdb.com/#account-creation
#      MOBYGAMES_API_KEY:  ''        # https://www.mobygames.com/info/api/
    volumes:
      - './romm/library:/romm/library'
      - './romm/assets:/romm/assets'
      - './romm/config:/romm/config'
    ports:
      - '8080:8080'
    depends_on:
      mariadb:
        condition: service_healthy  # 依赖数据库健康状态  
    networks:
      - default
      # 若 MariaDB 在另一个自定义网络中，需添加对应网络配置
      # - external_network

# 若 MariaDB 通过 Compose 管理，添加如下服务定义
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - './mariadb/data:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - default
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s  # 初始等待时间
      interval: 10s      # 检查间隔
      timeout: 5s       # 单次检查超时
      retries: 5        # 重试次数

networks:
  default:
    driver: bridge
  # 若需跨 Compose 文件共享网络，定义外部网络
  # external_network:
  #   external: true
